FROM centos:latest
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
#RUN yum update -y && yum install httpd -y
RUN yum install httpd -y
RUN mkdir -p /etc/apache2/sites/
RUN touch /etc/apache2/sites/default-apache.conf
RUN chown root:root /etc/apache2/sites/default-apache.conf
EXPOSE 80
CMD ["/usr/bin/apachectl" , "-D" , "FOREGROUND"]
