echo "script argrument list"
echo "\$* value = $*"
echo "\$@ value = $@"
echo "\$1 value = $1"
echo "\$2 value = $2"
echo "\$3 value = $3"
echo "\$4 value = $4"
echo "\$5 value = $5"
echo "\$# value = $#"
echo "\$$ value = $$"
