FROM centos:latest
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
RUN yum install httpd -y
RUN yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
#RUN yum install apache2 -y
#ADD default-apache.conf /etc/apache2/sites/
#RUN chown root:root /etc/apache2/sites/default-apache.conf
EXPOSE 80
CMD ["/usr/bin/apachectl" , "-D" , "FOREGROUND"]
