---
 - hosts: prod
   gather_facts: false
   tasks:
   - name: "webpage"
     file: dest=/var/www/html/index.html state=touch
   - name: "line"
     lineinfile: dest=/var/www/html/index.html line='this is shanmuk'
   - name: "webpage"
     service: name=httpd state=restarted 
