echo "script orguments list"
echo "\$* value = $*"
echo "\$@ value = $@"
echo "\$0 value = $0"
echo "\$1 vaule = $1"
echo "\$2 vaule = $2"
echo "\$3 vaule = $3"
echo "\$4 vaule = $4"
echo "\$5 vaule = $5"
echo "\$6 vaule = $6"
#echo "\$7 vaule = $7"
#echo "\$8 vaule = $8"
