---
 - hosts: all
   gather_facts: False
   tasks:
     - name: "copy the script"
       copy: src=/tmp/output.sh dest=/tmp/
     - name: "change perms"
       file: path=/tmp/output.sh owner=root group=root mode=777
     - name: exec the script
       script: /tmp/output.sh >> /tmp/output-info
     - name: "fetch the output"
       fetch: src=/tmp/output-info dest=/tmp/{{inventory_hostname}}-output flat=yes
