---
 - name: debug module case9
   hosts: all
   vars:
          os: "linux"
          cloud: "aws"
          tools: "devops"
   tasks:
    - name: file variable for printing variable
      debug:
        msg: "i love {{os}}"
