---
 - name: my kernel version
   hosts: all
   tasks:
    - name: kernel info
      command: uname -r
      register: kernel_info
      tags:
            - kernel
            - always
    - name: print output
      debug: var=kernel_info.stdout
      tags:
            - kernelout
            - always
    - name: os version
      shell: cat /etc/redhat-release
      register: os_ver
      tags:
         - never
         - os
    - name: output
      debug: var=os_ver.stdout
      tags:
         - never
         - osout

