---
  - name: copy sshd configuration file and start the service if incase any changes in file
    hosts: all
    tasks:
     - name: copy sshd configuration file
       synchronize: src=/etc/ssh/sshd_config dest=/tmp/
       register: edit
     - service: name=sshd state=restarted
       when: edit changed
